
	IFND	FUNC_MAIN
	xref	mt_init
	xref	_main
	xref	_copper_list
	xref	_reset_system
	xref	_reset_copper
	xref	_reset_vbi
	xref	_setup_vbi
	xref	_do_ints
	xref	_vbi_interupt
	xref	_setup_screens
	xref	_make_copper
	xref	_setup_keyboard
	xref	_reset_keyboard
	xref	_setup_libs
	xref	_DosBase
	xref	_GFXBase
	xref	_swap_screens
	xref	_showing
	xref	_scr_system
	xref	_toggle
	xref	_wait_vbi
	xref	_vbi_mouse
	xref	_setup_mouse
	xref	_move_pointer
	xref	_pointer_data
	xref	_setup_serial
	xref	_set_serial
	xref	_clear_serial
	xref	_r_ser_buff
	xref	_w_ser_buff
	xref	_ww_ser_buff
	xref	_read_serial
	xref	_write_serial
	xref	_Open
	xref	_Close
	xref	_Read
	xref	_Write
	xref	_Seek
	ENDC

	IFND	FUNC_BSS_F
	xref	_copper_shift1
	xref	_copper_shift2
	xref	_copper_screenptr1
	xref	_copper_screenptr2
	xref	_copper_screen1
	xref	_copper_screen2
	xref	_seed
	xref	_time
	xref	_copper_mem1
	xref	_copper_mem2
	xref	_screen_mem
	xref	_vbi_done
	xref	_w_screen
	xref	_d_screen
	xref	_b_screen
	xref	_old1_int_vec
	xref	_old2_int_vec
	xref	_da_flag
	xref	_iinkey
	xref	_key_on
	xref	_pal
	xref	_vbi_timer
	xref	_iiinkey
	xref	_joy1
	xref	_dx_joy
	xref	_dy_joy
	xref	_fire
	xref	_bullet_fire
	xref	_fire2
	xref	_mousex
	xref	_mousey
	xref	_mmousex
	xref	_mmousey
	xref	_right_button
	xref	_left_button
	xref	_mright_button
	xref	_mleft_button
	xref	_tog
	xref	_controler
	ENDC

	IFND	FUNC_DISPLAY
	xref	_display
	xref	_to_alpha
	xref	_myload_file
	xref	_mysave_file
	ENDC

	IFND	FUNC_SPRITES
	xref	_s8_draw
	xref	_s16_draw
	xref	_s32_draw
	xref	sprite_screen_width
	xref	lines_high
	ENDC
